name: smart-campus-dashboard
services:
    - name: dashboard
      source_dir: /
      github:
          repo: Mugabe-Hillary/smart-campus-dashboard
          branch: main
      build_command: |
          # Ensure requirements file exists
          if [ ! -f "requirements-modular.txt" ] && [ -f "requirements.txt" ]; then
              echo "Creating requirements-modular.txt from requirements.txt"
              cp requirements.txt requirements-modular.txt
          fi
          # List files for debugging
          echo "Files in build context:"
          ls -la
      run_command: streamlit run dashboard.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false
      environment_slug: python
      instance_count: 1
      instance_size_slug: basic-xxs
      envs:
          - key: DASHBOARD_PASSWORD
            value: your_secure_password_here
            type: SECRET
          - key: PYTHONUNBUFFERED
            value: "1"
      http_port: 8080
      routes:
          - path: /
